name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job za gradnjo backenda
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Kloniranje repozitorija
      uses: actions/checkout@v3

    - name: Setup Node.js  # Namestitev Node.js okolja
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules  # Caching odvisnosti
      uses: actions/cache@v3
      with:
        path: aplikacija/backend/node_modules  # Pot do mape node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('aplikacija/backend/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd aplikacija/backend
        npm ci

    - name: Upload backend artifacts  # Naložitev artefaktov za backend
      uses: actions/upload-artifact@v4
      with:
        name: build  # Ime artefakta
        path: |
          aplikacija/backend/  
          aplikacija/backend/node_modules/  # Pot do celotne kode in nameščenih odvisnosti

  # Job za testiranje backenda
  test-backend:
    needs: build-backend  # Testiranje se izvede po uspešni gradnji
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code  # Kloniranje repozitorija
      uses: actions/checkout@v3

    - name: Setup Node.js  # Namestitev Node.js okolja
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules  # Caching odvisnosti
      uses: actions/cache@v3
      with:
        path: aplikacija/backend/node_modules  # Pot do mape node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('aplikacija/backend/package-lock.json') }}  # Ključ za cache
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install dependencies  # Namestitev odvisnosti
      run: |
        cd aplikacija/backend
        npm install

    - name: Run tests with coverage  # Izvajanje testov s pokritostjo
      run: |
        cd aplikacija/backend
        npm run test:ci

    - name: Upload coverage report  # Naložitev poročila o pokritosti kode
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage  # Ime artefakta
        path: aplikacija/backend/coverage/  # Pot do poročila o pokritosti kode
